# fly.toml app configuration file generated for leerming on 2023-10-03T14:02:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "leerming"
primary_region = "mad"

[build]
  dockerfile = "docker/Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
