# Generated by Django 4.2.6 on 2023-10-16 12:39
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gifts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gifts_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gifts_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
