# Generated by Django 4.2.6 on 2023-10-15 14:17
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0002_alter_gift_recipient_alter_gift_sender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gift",
            old_name="processed_at",
            new_name="opened_at",
        ),
    ]
