# Generated by Django 4.2.6 on 2023-10-20 16:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadeddocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("YOUTUBE_VIDEO", "Vidéo Youtube"),
                    ("TEXT_DOC", "Document texte"),
                    ("HTML_DOC", "Page web"),
                    ("RAW_TEXT", "Texte brut"),
                ],
                max_length=255,
            ),
        ),
    ]
