# Generated by Django 4.2.5 on 2023-10-01 13:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import django_lifecycle.mixins
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "review_days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            choices=[
                                (0, "Lundi"),
                                (1, "Mardi"),
                                (2, "Mercredi"),
                                (3, "Jeudi"),
                                (4, "Vendredi"),
                                (5, "Samedi"),
                                (6, "Dimanche"),
                            ]
                        ),
                        size=None,
                        verbose_name="Jours de révision",
                    ),
                ),
                ("review_time", models.TimeField(verbose_name="Heure de révision")),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, django_lifecycle.mixins.LifecycleModelMixin),
        ),
    ]
