# Generated by Django 4.2.5 on 2023-09-22 13:20

from django.db import migrations, models
import django.utils.timezone
import django_lifecycle.mixins
import django_pydantic_field._migration_serializers
import django_pydantic_field.fields
import leerming.profiles.models
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "review_days",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        schema=django_pydantic_field._migration_serializers.GenericContainer(
                            list, (leerming.profiles.models.Profile.Weekday,)
                        ),
                    ),
                ),
                ("review_time", models.TimeField()),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, django_lifecycle.mixins.LifecycleModelMixin),
        ),
    ]
