# Generated by Django 4.2.6 on 2023-10-10 15:42
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_profile_email_notifications_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=models.CharField(
                default="UTC", max_length=50, verbose_name="Fuseau horaire"
            ),
        ),
    ]
