# Generated by Django 4.2.6 on 2023-10-14 11:37
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_profile_full_name_profile_short_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="review_time",
            field=models.TimeField(default="18:00", verbose_name="Heure de révision"),
        ),
    ]
