# Generated by Django 4.2.5 on 2023-10-01 13:19

import datetime
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "score_percentage",
                    models.IntegerField(default=0, verbose_name="Score %"),
                ),
                (
                    "creation_date",
                    models.DateField(
                        default=datetime.date.today,
                        editable=False,
                        verbose_name="Créé le",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminé le"
                    ),
                ),
                ("flashcards", models.ManyToManyField(to="flashcards.flashcard")),
            ],
            options={
                "ordering": ("-creation_date",),
            },
        ),
    ]
