# Generated by Django 4.2.5 on 2023-10-05 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_q', '0017_task_cluster_alter'),
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('result_task', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_q.task')),
                ('reviewers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('schedule', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_q.schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
