# Generated by Django 4.2.5 on 2023-09-25 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ("-creation_date",)},
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.AddField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Créé"),
                    ("ON_GOING", "En cours"),
                    ("DONE", "Terminé"),
                ],
                default="CREATED",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
