# Generated by Django 4.2.6 on 2023-10-09 10:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0006_alter_flashcard_topic"),
        ("reviews", "0003_schedulemanager"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="topics",
            field=models.ManyToManyField(to="flashcards.topic"),
        ),
    ]
