# Generated by Django 4.2.5 on 2023-10-01 13:19

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlashCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("FRONT_BACK", "Deux faces"),
                            ("FILL_IN_THE_GAP", "Remplissage"),
                        ],
                        default="FILL_IN_THE_GAP",
                        max_length=20,
                        verbose_name="Type de carte",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        help_text="Indique la difficulté de la carte, de 1 à 7 (le niveau le plus difficile).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "last_review_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de dernière révision"
                    ),
                ),
                (
                    "mastered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Maîtrisée à"
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        max_length=250, verbose_name="Question / Texte à remplir"
                    ),
                ),
                ("answer", models.CharField(max_length=200, verbose_name="Réponse")),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
