# Generated by Django 4.2.5 on 2023-09-25 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0002_flashcard_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flashcard",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="level",
            field=models.IntegerField(
                default=1,
                help_text="Indique la difficulté de la carte, de 1 à 7 (le niveau le plus difficile).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
                verbose_name="Niveau",
            ),
        ),
    ]
