# Generated by Django 4.2.6 on 2023-10-06 14:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flashcard",
            name="last_review_date",
        ),
        migrations.AddField(
            model_name="flashcard",
            name="next_review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de la prochaine révision"
            ),
        ),
    ]
