# Generated by Django 4.2.6 on 2023-10-14 11:37
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0006_alter_flashcard_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="card_type",
            field=models.CharField(
                choices=[
                    ("FRONT_BACK", "Recto / Verso"),
                    ("FILL_IN_THE_GAP", "Remplissage"),
                ],
                default="FILL_IN_THE_GAP",
                max_length=20,
                verbose_name="Type de carte",
            ),
        ),
    ]
