# Generated by Django 4.2.6 on 2023-10-15 15:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0007_alter_flashcard_card_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flashcard",
            options={},
        ),
        migrations.AddConstraint(
            model_name="flashcard",
            constraint=models.UniqueConstraint(
                fields=("owner", "question", "answer"), name="unique_flashcard"
            ),
        ),
    ]
