# Generated by Django 4.2.5 on 2023-09-19 19:28

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FillInTheGapCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "last_reviewed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de dernière révision"
                    ),
                ),
                (
                    "mastered_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de maîtrise"
                    ),
                ),
                ("text_with_gap", models.TextField(verbose_name="Texte à remplir")),
                ("answer", models.TextField(max_length=100, verbose_name="Réponse")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FrontBackCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "last_reviewed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de dernière révision"
                    ),
                ),
                (
                    "mastered_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de maîtrise"
                    ),
                ),
                ("question", models.TextField(verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Réponse")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
